Больше деталей
htmlacademy-javascript/1483111-kekstagram-22 pull request #3
Opened 2021-02-08 14:36 UTC by solusmax

2021-02-08 14:38 UTC, solusmax commented on js/main.js
> +  quantity: 25,
Для заранее известных данных сначала использовал КОН_СТАНТЫ, но количество аргументов, которые передаются от функции к функции выросло до каких-то безумных размеров, и я вспомнил, что в тренажёрах для решения этой проблемы использовались объекты, поэтому объединил все моковые данные в один объект, который теперь и передаётся в аргументах.

2021-02-08 21:18 UTC, nuposyatina requested changes
Молодчина, в целом работа очень хорошая. =) Жду исправлений.

2021-02-08 21:18 UTC, nuposyatina commented on js/main.js
> +    likes: getRandomInteger(15, 200),
Нужно вынести числовые значения в константы и использовать их. Критерий [Д19](https://up.htmlacademy.ru/javascript/22/criteries#d19) запрещает использование магических чисел.

2021-02-09 18:24 UTC, nuposyatina approved these changes
Все замечания исправлены, молодчина) Можно приступать к следующей домашке

2021-02-09 18:28 UTC, merged