Отрисуй меня полностью (часть 2)
htmlacademy-javascript/1483111-kekstagram-22 pull request #6
Opened 2021-03-01 22:03 UTC by solusmax

2021-03-01 22:16 UTC, solusmax commented on js/big-picture.js
> +const bigPictureCommentsNode = bigPictureNode.querySelector('.social__comments');
Вызывает сомнения, адекватно ли я именую переменные, а именно, нужно ли в таких случаях добавлять для каждой переменной префикс `bigPicture`, учитывая, что это модуль, и других переменных тут нет. Может, стоило просто сделать вот так:
`const bigPictureNode`
`const closeNode`
`const imgNode`
`const descriptionNode`
`const likesCounterNode`
`const commentsCounterNode`
`const commentsNode`

2021-03-02 19:36 UTC, nuposyatina requested changes
Нужно немного подправить рендер комментариев. В остальном все отлично =) продолжай в том же духе!

2021-03-02 19:36 UTC, nuposyatina commented on js/big-picture.js
> +  bigPictureCommentsNode.innerHTML = '';
Использование innerHTML по критерию [Б27](https://up.htmlacademy.ru/javascript/22/criteries#b27) в принципе допускается, если вставляет не пользовательский текст, а созданный самим программистом. Поэтому можно оставить и так, но я предлагаю другой вариант: в цикле (здесь лучше использовать while) проверяем, что у bigPicturesCommentNode есть дочерняя нода (можно с помощью firstChild). Если есть, то удаляем дочернюю ноду. Если нет, выходим из цикла. Звучит парадоксально, но такой способ  работает быстрее innerHTML. Это мне более опытный разработчик подсказал =) Да и точно не придерутся во время проверки к innerHTML

2021-03-02 19:36 UTC, nuposyatina commented on js/big-picture.js
> +  bigPictureCommentsNode.innerHTML = '';
Естественно удаление комментариев нужно вынести в отдельную функцию =)

2021-03-02 19:36 UTC, nuposyatina commented on js/big-picture.js
> +}
Здесь нарушается критерий [Б27](https://up.htmlacademy.ru/javascript/22/criteries#b27). Эту функцию по созданию комментария ты скорее всего будешь использовать не только для отрисовки комментов, которые уже есть, но и для того чтобы отрисовать комментарий, который создает пользователь сервиса. А пользователь может быть злоумышленником и вставить в эту форму скрипт, который похищает твои данные или ломает сервис =)
Да и всяко удобней работать в js с dom-элементами, а не с версткой.
Поэтому здесь нужно создавать ноды с помощью createElement и добавлять им нужные свойства.

2021-03-02 19:36 UTC, nuposyatina commented on js/big-picture.js
> +  });
Когда переделаешь функцию createCommentHtml (нужно будет сменить ее название, например на createComment), в insertAdjacentHTML не будет необходимости. Можно будет использовать обычный appendChild.

2021-03-02 22:35 UTC, nuposyatina approved these changes
Все замечания учтены, домашку принимаю. Молодец что пытаешься досконально разобраться в вопросах)

2021-03-02 22:35 UTC, merged