Помощь друга (часть 1)
htmlacademy-javascript/1483111-kekstagram-22 pull request #7
Opened 2021-03-05 08:21 UTC by solusmax

2021-03-06 10:18 UTC, nuposyatina requested changes
Молодец, хорошо справился со своей задачей) Давай теперь немного порефакторим код. 
p.s. Предлагаю scale и effects разделить на 2 модуля, потому что получается довольно большая простыня, ориентироваться тяжеловато.

2021-03-06 10:18 UTC, nuposyatina commented on js/upload-picture.js
> +  sliderNode.noUiSlider.on('update', onSliderUpdate(filterName, unit));
И вот этот кусочек тоже можно вынести в отдельную функцию.

2021-03-06 10:18 UTC, nuposyatina commented on js/upload-picture.js
> +    if (effectRadioNode.value === 'none') {
Вынеси 'none' в константу. Потому что если в будущем будет решено сделать так, что отсутствие эффекта — пустая строка, то тебе по всему коду придется искать none

2021-03-06 21:43 UTC, solusmax commented on js/upload-picture.js
> +const effectRadioButtons = uploadModalNode.querySelectorAll('.effects__list [name="effect"]');
Сработал принцип «сначала сделал лишь бы работало, а потом забыл отрефакторить»

2021-03-06 21:43 UTC, solusmax commented on js/upload-picture.js
> +  if (!(currentScaleValue <= ScaleSettings.MIN)) {
Здесь тоже сработал принцип «сначала сделал лишь бы работало, а потом забыл отрефакторить» :D

2021-03-06 22:04 UTC, solusmax commented on js/upload-picture.js
> +const uploadButtonNode = document.querySelector('#upload-file');
Вообще, селектор `#upload-file` просто [указан в ТЗ](https://up.htmlacademy.ru/javascript/22/project/kekstagram#kekstagram-1-2). Интуитивно я решил проследововать в этом вопросе ТЗ, чтобы не было никаких проблем на защите.

Тем более я не знаю по какому, собственно, принципу нужно ориентироваться при выборе селектора. В CSS селекторы по `id` вообще почти под полным запретом. А в JS мне казалось, что лучше выбирать `id`, если есть такая возможность, а если нет, то тогда уж класс. Мол, так надёжнее, ибо никогда не выберется не то, что нужно. Но, исходя из твоего комментария, видимо, нужно просто стараться руководствоваться принципом единиообразия. Так что сейчас поменял везде, где можно, селекторы по `id` на селекторы по классу. Селекторы по `id` остались только для `<template>`

2021-03-07 01:32 UTC, solusmax commented on js/upload-picture.js
> +const renderEffect = (effectRadioNode) => {
Пока рефакторил, обнаружил, что можно вынести обработчик в отдельную функцию `const onEffectRadioChange = (effectName) => {}` и просто передавать ему *один* раз `effectRadioNode.value`, и тогда даже деструктуризация не нужна, потому что дальше везде, в том числе в `renderEffect`, просто обращение к `effectName`

2021-03-07 01:34 UTC, solusmax commented on js/upload-picture.js
> +const renderEffect = (effectRadioNode) => {
По-моему, так лучше, но если нет, то переделаю с деструктуризацией

2021-03-07 01:45 UTC, solusmax commented on js/upload-picture.js
> +  const defaultVaule = Effects[effectName].DEFAULT;
> В итоге вместо 6 строчек в твоей функции у тебя будет одна:
>
> `const { filterName, unit, ... } = getEffectValues;`

Не уверен, правильно ли сделал, но в итоге вместо `const { filterName, unit, min, max, step, defaultValue } = getEffectValues(effectName);` у меня просто `const effectValues = getEffectValues(effectName);`, и я передаю этот объект `effectValues` по функциям, а в объявлениях функций, если надо, уже использую деструктуризацию. Опять же, если так по каким-то причинам не стоило делать, то переделаю снова, но мне показалось, что так код получится ещё проще, и при этом вроде бы ничего не страдает

2021-03-08 09:30 UTC, nuposyatina approved these changes
Красота)

2021-03-08 09:30 UTC, merged