Помощь друга (часть 2)
htmlacademy-javascript/1483111-kekstagram-22 pull request #8
Opened 2021-03-08 17:01 UTC by solusmax

2021-03-08 19:01 UTC, nuposyatina requested changes
Как всегда хорошая работа) жду исправлений

2021-03-08 19:01 UTC, nuposyatina commented on js/util.js
> +const isStringEmpty = (string) => string.search(/[\S]+/) === -1;
Любишь ты регулярки) Можно ж было просто сделать так: `string.trim() === ''`

2021-03-09 07:29 UTC, solusmax commented on js/hashtags-validation.js
> +const getHashtags = (string) => string.trim().split(/[\s]+/);
Если использовать `.split(' ')`, то не будут учитываться ситуации, когда пользователь по ошибке поставил между хештегами два пробела и более. Массив `hashtags` получится вот такой:

![image](https://user-images.githubusercontent.com/66680032/110433168-299b0200-80c1-11eb-8f89-c2969166da6f.png)

Кроме того, благодаря регулярке можно в качестве разделителей использовать табуляцию. Редкий юзкейс, но всё же возможный

2021-03-09 07:35 UTC, solusmax commented on js/util.js
> +const isStringEmpty = (string) => string.search(/[\S]+/) === -1;
> Любишь ты регулярки)

Это да :3 Но в данном случае твой способ действительно гораздо читабельнее.

2021-03-09 09:37 UTC, solusmax commented on js/hashtags-validation.js
> +      reportNoError(hashtagsFieldNode);
Тут всё равно дополнительная вложенность получилась. Можно, конечно вот так сделать:

```
if (isStringEmpty(hashtagsString) && hashtagsFieldNode.validity.customError) {
  reportNoError(hashtagsFieldNode);
  return;
}

if (isStringEmpty(hashtagsString)) {
  return;
}
```

Но мне кажется, так ещё хуже будет. Ещё есть вариант вообще избавиться от проверки `hashtagsFieldNode.validity.customError`, ибо от вызова `reportNoError` на пустом поле, по сути, нет никакого вреда, кроме того, что отрабатывают лишние операции. Но я не знаю как в таких случаях поступают. По мне так лучше тот вариант, который сейчас закоммичен

2021-03-09 17:42 UTC, merged